// ESTANTE — dados dos livros
// Importado da sua exportação do Goodreads.
// Para adicionar um livro novo, copie um bloco { ... } inteiro,
// cole antes do ] final e preencha os campos.
//
// status: "lido" | "lendo" | "quero-ler"
// nota: 0 a 5 (0 = sem nota ainda)
// isbn: usado pra buscar a capa automaticamente (Open Library) — deixe "" se não souber
// tags: lista livre, ex: ["russo", "filosofia"]

const BOOKS = [
  {
    titulo: "Our Thoughts Determine Our Lives:  The Life and Teachings of Elder Thaddeus of Vitovnica",
    autor: "Thaddeus of Vitovnica",
    tags: [],
    paginas: 212,
    status: "quero-ler",
    nota: 0,
    dataLeitura: null,
    resenha: "",
    isbn: "9781887904193"
  },
  {
    titulo: "Exophony: Voyages Outside the Mother Tongue",
    autor: "Yōko Tawada",
    tags: ["alemão", "inglês", "japonês"],
    paginas: 192,
    status: "lido",
    nota: 3,
    dataLeitura: "2026-03-03",
    resenha: "",
    isbn: "9780811237871"
  },
  {
    titulo: "The Earthquake in Chile",
    autor: "Heinrich von Kleist",
    tags: [],
    paginas: 17,
    status: "quero-ler",
    nota: 0,
    dataLeitura: null,
    resenha: "",
    isbn: ""
  },
  {
    titulo: "Hojoki: Visions of a Torn World",
    autor: "Kamo no Chōmei",
    tags: ["japonês"],
    paginas: 96,
    status: "lido",
    nota: 4,
    dataLeitura: null,
    resenha: "",
    isbn: "9781880656228"
  },
  {
    titulo: "O Deserto dos Tártaros",
    autor: "Dino Buzzati",
    tags: ["italiano"],
    paginas: 256,
    status: "lido",
    nota: 4,
    dataLeitura: "2025-12-31",
    resenha: "",
    isbn: "9789896230999"
  },
  {
    titulo: "Kafka à Beira-Mar",
    autor: "Haruki Murakami",
    tags: ["japonês"],
    paginas: 592,
    status: "lido",
    nota: 4,
    dataLeitura: null,
    resenha: "",
    isbn: "9789896603151"
  },
  {
    titulo: "Memórias do Subsolo",
    autor: "Fyodor Dostoevsky",
    tags: ["russo"],
    paginas: 152,
    status: "lido",
    nota: 4,
    dataLeitura: null,
    resenha: "",
    isbn: "9788573261851"
  },
  {
    titulo: "Os Irmãos Karamázov",
    autor: "Fyodor Dostoevsky",
    tags: ["russo"],
    paginas: 592,
    status: "lido",
    nota: 5,
    dataLeitura: "2015-01-01",
    resenha: "",
    isbn: "9788573264111"
  },
  {
    titulo: "Catecismo Maior de São Pio X",
    autor: "Pope Pius X",
    tags: ["português"],
    paginas: 242,
    status: "lido",
    nota: 5,
    dataLeitura: null,
    resenha: "",
    isbn: ""
  },
  {
    titulo: "Melhores Poemas de Álvares de Azevedo",
    autor: "Álvares de Azevedo",
    tags: ["português"],
    paginas: 208,
    status: "lido",
    nota: 4,
    dataLeitura: "2017-01-01",
    resenha: "",
    isbn: "9788526000223"
  },
  {
    titulo: "O Jogador",
    autor: "Fyodor Dostoevsky",
    tags: ["russo"],
    paginas: 165,
    status: "lido",
    nota: 4,
    dataLeitura: null,
    resenha: "",
    isbn: "9789722327442"
  },
  {
    titulo: "O Grande Gatsby",
    autor: "Equipe East Press",
    tags: ["inglês"],
    paginas: 208,
    status: "lido",
    nota: 5,
    dataLeitura: null,
    resenha: "",
    isbn: "9788525428769"
  },
  {
    titulo: "O conde de Monte Cristo: edição bolso de luxo (Clássicos Zahar)",
    autor: "Alexandre Dumas",
    tags: ["francês"],
    paginas: 1823,
    status: "lido",
    nota: 5,
    dataLeitura: "2023-08-23",
    resenha: "",
    isbn: "9788537808801"
  },
  {
    titulo: "ABC of Reading",
    autor: "Ezra Pound",
    tags: [],
    paginas: 210,
    status: "quero-ler",
    nota: 0,
    dataLeitura: null,
    resenha: "",
    isbn: "9780811201513"
  },
  {
    titulo: "O Matrimonio",
    autor: "Søren Kierkegaard",
    tags: ["dinamarquês"],
    paginas: 140,
    status: "lido",
    nota: 3,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9788585480684"
  },
  {
    titulo: "Em Busca do Tempo Perdido – Dicionário de Nomes & Lugares",
    autor: "Michel Erman",
    tags: ["francês"],
    paginas: 192,
    status: "lido",
    nota: 0,
    dataLeitura: null,
    resenha: "",
    isbn: "9788525058768"
  },
  {
    titulo: "Wagner em Bayreuth",
    autor: "Friedrich Nietzsche",
    tags: ["alemão"],
    paginas: 126,
    status: "lido",
    nota: 2,
    dataLeitura: null,
    resenha: "",
    isbn: ""
  },
  {
    titulo: "A Arte da Guerra",
    autor: "Sun Tzu",
    tags: ["chinês"],
    paginas: 101,
    status: "lido",
    nota: 2,
    dataLeitura: "2017-01-01",
    resenha: "",
    isbn: "9789722519885"
  },
  {
    titulo: "The Miserable Mill (A Series of Unfortunate Events, #4)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 194,
    status: "lido",
    nota: 2,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780439272636"
  },
  {
    titulo: "Poemas",
    autor: "Lord Byron",
    tags: ["inglês"],
    paginas: 168,
    status: "lido",
    nota: 3,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788577150786"
  },
  {
    titulo: "À Sombra das Raparigas em Flor (Em Busca do Tempo Perdido, #2)",
    autor: "Marcel Proust",
    tags: ["francês"],
    paginas: 672,
    status: "lido",
    nota: 3,
    dataLeitura: "2020-01-01",
    resenha: "",
    isbn: "9788525042262"
  },
  {
    titulo: "Guia politicamente incorreto da História do Brasil",
    autor: "Leandro Narloch",
    tags: ["português"],
    paginas: 304,
    status: "lido",
    nota: 3,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9788544102787"
  },
  {
    titulo: "Beleza",
    autor: "Roger Scruton",
    tags: ["inglês"],
    paginas: 222,
    status: "lido",
    nota: 3,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788580331455"
  },
  {
    titulo: "O Alquimista",
    autor: "Paulo Coelho",
    tags: ["português"],
    paginas: 240,
    status: "lido",
    nota: 3,
    dataLeitura: "2012-01-01",
    resenha: "",
    isbn: "9789727110797"
  },
  {
    titulo: "The Hostile Hospital (A Series of Unfortunate Events, #8)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 272,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9781405206129"
  },
  {
    titulo: "Bobok",
    autor: "Fyodor Dostoevsky",
    tags: ["russo"],
    paginas: 22,
    status: "lido",
    nota: 3,
    dataLeitura: "2019-01-01",
    resenha: "",
    isbn: "9781419110429"
  },
  {
    titulo: "The Wide Window (A Series of Unfortunate Events, #3)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 214,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064407687"
  },
  {
    titulo: "The Grim Grotto (A Series of Unfortunate Events, #11)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 323,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064410144"
  },
  {
    titulo: "The Austere Academy (A Series of Unfortunate Events, #5)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 221,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064408639"
  },
  {
    titulo: "Mau Começo (Desventuras em Série, #1)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 151,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9788535900941"
  },
  {
    titulo: "The Carnivorous Carnival (A Series of Unfortunate Events, #9)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 286,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064410120"
  },
  {
    titulo: "The Reptile Room (A Series of Unfortunate Events, #2)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 192,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "The End (A Series of Unfortunate Events, #13)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 353,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064410168"
  },
  {
    titulo: "Os Sofrimentos do Jovem Werther",
    autor: "Johann Wolfgang von Goethe",
    tags: ["alemão"],
    paginas: 192,
    status: "lido",
    nota: 3,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "The Vile Village (A Series of Unfortunate Events, #7)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 272,
    status: "lido",
    nota: 3,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780060566227"
  },
  {
    titulo: "Coração devotado à morte: O sexo e o sagrado em Tristão e Isolda de Wagner",
    autor: "Roger Scruton",
    tags: ["inglês"],
    paginas: 286,
    status: "lido",
    nota: 3,
    dataLeitura: null,
    resenha: "",
    isbn: "9788580330076"
  },
  {
    titulo: "Fausto (Spanish Edition)",
    autor: "Goethe W Johan",
    tags: ["alemão"],
    paginas: 178,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9781974623228"
  },
  {
    titulo: "Kashtanka and Other Stories (1887) (Russian Edition)",
    autor: "Anton Chekhov",
    tags: ["russo"],
    paginas: 496,
    status: "lido",
    nota: 4,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "The Way up to Heaven",
    autor: "Roald Dahl",
    tags: ["inglês"],
    paginas: 0,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "Ante as sombras, moacir de almeida, o poeta e sua obra",
    autor: "Luiz Carlos de Oliveira Cerqueira",
    tags: ["português"],
    paginas: 166,
    status: "lido",
    nota: 4,
    dataLeitura: "2018-01-01",
    resenha: "mrs heggendorn...",
    isbn: ""
  },
  {
    titulo: "Sonetos Completos de Florbela Espanca",
    autor: "Florbela Espanca",
    tags: ["português"],
    paginas: 193,
    status: "lido",
    nota: 4,
    dataLeitura: "2020-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "Guia Politicamente Incorreto do Futebol",
    autor: "Jones Rossi",
    tags: ["português"],
    paginas: 416,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9788580449907"
  },
  {
    titulo: "A alma do mundo",
    autor: "Roger Scruton",
    tags: ["inglês"],
    paginas: 238,
    status: "lido",
    nota: 4,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788501109026"
  },
  {
    titulo: "Literature Class, Berkeley 1980",
    autor: "Julio Cortázar",
    tags: ["espanhol"],
    paginas: 280,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9780811225342"
  },
  {
    titulo: "Five Stories by Kunikida Doppo",
    autor: "Doppo Kunikida",
    tags: ["japonês"],
    paginas: 69,
    status: "lido",
    nota: 4,
    dataLeitura: "2017-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "O rosto de Deus",
    autor: "Roger Scruton",
    tags: ["inglês"],
    paginas: 240,
    status: "lido",
    nota: 4,
    dataLeitura: "2019-01-01",
    resenha: "",
    isbn: "9788580332216"
  },
  {
    titulo: "Aphorisms of Oscar Wilde",
    autor: "Oscar Wilde",
    tags: ["inglês"],
    paginas: 72,
    status: "lido",
    nota: 4,
    dataLeitura: "2021-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "Polonaise - The Life of Chopin",
    autor: "Guy de Pourtalès",
    tags: ["alemão"],
    paginas: 360,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9781406745719"
  },
  {
    titulo: "No caminho de Swann (Em busca do tempo perdido, #1)",
    autor: "Marcel Proust",
    tags: ["francês"],
    paginas: 560,
    status: "lido",
    nota: 4,
    dataLeitura: "2019-01-01",
    resenha: "",
    isbn: "9788525042255"
  },
  {
    titulo: "Stefan George: Die Entdeckung des Charisma",
    autor: "Thomas Karlauf",
    tags: ["alemão"],
    paginas: 816,
    status: "lido",
    nota: 4,
    dataLeitura: "2022-01-01",
    resenha: "",
    isbn: "9783896671516"
  },
  {
    titulo: "Madame Bovary",
    autor: "Gustave Flaubert",
    tags: ["francês"],
    paginas: 329,
    status: "lido",
    nota: 4,
    dataLeitura: "2013-01-01",
    resenha: "",
    isbn: "9780192840394"
  },
  {
    titulo: "A Fantástica Fábrica de Chocolate (Charlie Bucket, #1)",
    autor: "Roald Dahl",
    tags: ["inglês"],
    paginas: 158,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9788533609822"
  },
  {
    titulo: "The Slippery Slope (A Series of Unfortunate Events, #10)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 337,
    status: "lido",
    nota: 4,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064410137"
  },
  {
    titulo: "História da Beleza",
    autor: "Umberto Eco",
    tags: ["italiano"],
    paginas: 440,
    status: "lido",
    nota: 4,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788501068620"
  },
  {
    titulo: "A Túlipa Negra",
    autor: "Alexandre Dumas",
    tags: ["francês"],
    paginas: 224,
    status: "lido",
    nota: 4,
    dataLeitura: "2008-01-01",
    resenha: "",
    isbn: "9789722635868"
  },
  {
    titulo: "Hamlet",
    autor: "William Shakespeare",
    tags: ["inglês"],
    paginas: 289,
    status: "lido",
    nota: 4,
    dataLeitura: "2021-01-01",
    resenha: "",
    isbn: "9780521618748"
  },
  {
    titulo: "O homem que calculava",
    autor: "Malba Tahan",
    tags: ["português"],
    paginas: 300,
    status: "lido",
    nota: 4,
    dataLeitura: "2010-01-01",
    resenha: "",
    isbn: "9788501061966"
  },
  {
    titulo: "The Ersatz Elevator (A Series of Unfortunate Events, #6)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 259,
    status: "lido",
    nota: 4,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780060566210"
  },
  {
    titulo: "The Penultimate Peril (A Series of Unfortunate Events, #12)",
    autor: "Lemony Snicket",
    tags: ["inglês"],
    paginas: 353,
    status: "lido",
    nota: 4,
    dataLeitura: "2009-01-01",
    resenha: "",
    isbn: "9780064410151"
  },
  {
    titulo: "Macário",
    autor: "Álvares de Azevedo",
    tags: ["português"],
    paginas: 112,
    status: "lido",
    nota: 4,
    dataLeitura: "2020-01-01",
    resenha: "",
    isbn: "9788525410498"
  },
  {
    titulo: "A História Trágica do Doutor Fausto",
    autor: "Christopher Marlowe",
    tags: ["alemão"],
    paginas: 128,
    status: "lido",
    nota: 4,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "O Livro do Travesseiro",
    autor: "Sei Shōnagon",
    tags: ["japonês"],
    paginas: 616,
    status: "lido",
    nota: 4,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788573265156"
  },
  {
    titulo: "We: Understanding the Psychology of Romantic Love",
    autor: "Robert A. Johnson",
    tags: ["inglês"],
    paginas: 204,
    status: "lido",
    nota: 4,
    dataLeitura: "2017-01-01",
    resenha: "",
    isbn: "9780062504364"
  },
  {
    titulo: "Eu sou um gato",
    autor: "Natsume Sōseki",
    tags: ["japonês"],
    paginas: 488,
    status: "lido",
    nota: 4,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788574481388"
  },
  {
    titulo: "O Retrato de Dorian Gray",
    autor: "Stanislas Gros",
    tags: ["inglês"],
    paginas: 72,
    status: "lido",
    nota: 5,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788535919981"
  },
  {
    titulo: "Em Busca do Tempo Perdido - mangá",
    autor: "Marcel Proust",
    tags: ["francês"],
    paginas: 400,
    status: "lido",
    nota: 5,
    dataLeitura: "2021-01-01",
    resenha: "",
    isbn: "9788525432308"
  },
  {
    titulo: "Leonardo da Vinci",
    autor: "Walter Isaacson",
    tags: ["inglês"],
    paginas: 600,
    status: "lido",
    nota: 5,
    dataLeitura: "2020-01-01",
    resenha: "",
    isbn: "9781501139154"
  },
  {
    titulo: "Maihime",
    autor: "Ōgai Mori",
    tags: ["japonês"],
    paginas: 17,
    status: "lido",
    nota: 5,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: ""
  },
  {
    titulo: "La Vie de Franz Liszt",
    autor: "Guy de Pourtalès",
    tags: ["alemão"],
    paginas: 320,
    status: "lido",
    nota: 5,
    dataLeitura: "2016-01-01",
    resenha: "",
    isbn: "9782070374427"
  },
  {
    titulo: "Crime e Castigo",
    autor: "Fiódor   Dostoiévski",
    tags: ["russo"],
    paginas: 562,
    status: "lido",
    nota: 5,
    dataLeitura: "2015-01-01",
    resenha: "",
    isbn: "9788573262087"
  },
  {
    titulo: "Os Irmãos Karamázov",
    autor: "Fyodor Dostoevsky",
    tags: ["russo"],
    paginas: 1040,
    status: "lido",
    nota: 5,
    dataLeitura: "2015-01-01",
    resenha: "",
    isbn: "9788573264098"
  },
  {
    titulo: "Dracula",
    autor: "Bram Stoker",
    tags: ["inglês"],
    paginas: 488,
    status: "lido",
    nota: 5,
    dataLeitura: "2022-01-01",
    resenha: "",
    isbn: "9780393970128"
  },
  {
    titulo: "Kashtanka",
    autor: "Anton Chekhov",
    tags: ["russo"],
    paginas: 32,
    status: "lido",
    nota: 5,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9780152005399"
  },
  {
    titulo: "O mestre e Margarida",
    autor: "Mikhail Bulgakov",
    tags: ["russo"],
    paginas: 456,
    status: "lido",
    nota: 5,
    dataLeitura: "2020-01-01",
    resenha: "",
    isbn: "9788579620010"
  },
  {
    titulo: "The Divine Comedy: Inferno - Purgatorio - Paradiso",
    autor: "Dante Alighieri",
    tags: ["italiano"],
    paginas: 798,
    status: "lido",
    nota: 5,
    dataLeitura: "2020-01-01",
    resenha: "",
    isbn: "9780679433132"
  },
  {
    titulo: "O Grande Gatsby",
    autor: "F. Scott Fitzgerald",
    tags: ["inglês"],
    paginas: 256,
    status: "lido",
    nota: 5,
    dataLeitura: "2018-01-01",
    resenha: "",
    isbn: "9788563560292"
  },
  {
    titulo: "Ratos e Homens",
    autor: "John Steinbeck",
    tags: ["inglês"],
    paginas: 99,
    status: "lido",
    nota: 5,
    dataLeitura: "2017-01-01",
    resenha: "",
    isbn: "9789897110054"
  },
  {
    titulo: "Salomé",
    autor: "Oscar Wilde",
    tags: ["inglês"],
    paginas: 64,
    status: "lido",
    nota: 5,
    dataLeitura: "2021-01-01",
    resenha: "",
    isbn: "9780486421278"
  },
];